<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DbSignal.SqlServer\DbSignal.SqlServer.csproj" />
    <ProjectReference Include="..\DbSignal.Conformance\DbSignal.Conformance.csproj" />
  </ItemGroup>

</Project>
